#!/bin/bash
yum install -y httpd
# install setuptools
wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python
# install beautifulsoup
easy_install beautifulsoup4
# install html5lib
easy_install html5lib
# install pyExcelerator
easy_install pyExcelerator
